use Mix.Config

# For production, don't forget to configure the url host
# to something meaningful, Phoenix uses this information
# when generating URLs.
#
# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix phx.digest` task,
# which you should run after static files are built and
# before starting your production server.
config :tldr_event_sourcing, TldrEventSourcingWeb.Endpoint,
  http: [:inet6, port: System.get_env("PORT") || 4000],
  url: [scheme: "https", host: "tldr-event-sourcing.herokuapp.com/", port: 443],
  force_ssl: [rewrite_on: [:x_forwarded_proto]],
  secret_key_base: Map.fetch!(System.get_env(), "SECRET_KEY_BASE"),
  check_origin: ["https://tldr-event-sourcing.herokuapp.com/"]


config :tldr_event_sourcing, TldrEventSourcingWeb.Auth.Guardian,
  issuer: "tldr_event_sourcing",
  secret_key: Map.fetch!(System.get_env(), "GUARDIAN_SECRET")

config :tldr_event_sourcing, TldrEventSourcing.Repo,
  url: System.get_env("DATABASE_URL"),
  pool_size:  String.to_integer(System.get_env("POOL_SIZE") || "10"),
  ssl: true

# Do not print debug messages in production
config :logger, level: :info
